# Generated by Django 2.2.12 on 2020-05-10 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userDNI', models.CharField(max_length=20, verbose_name='ID de el usuario')),
                ('nombreUser', models.CharField(max_length=255, verbose_name='Nombre')),
                ('profecionUser', models.CharField(max_length=255, verbose_name='Profecion')),
                ('fotoUser', models.ImageField(default='user.png', upload_to='', verbose_name='foto de perfil')),
                ('telUser', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=255, verbose_name='direccion de usuario')),
                ('generoUser', models.CharField(choices=[('Femenino', 'F'), ('Masculino', 'M'), ('Otro', 'O')], default='O', max_length=10, verbose_name='Genero')),
                ('upData', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='modificado')),
            ],
            options={
                'verbose_name': 'dato de usuario',
                'verbose_name_plural': 'Datos de usuarios ',
            },
        ),
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreHabilidad', models.CharField(max_length=255, verbose_name='Nombre de la habilidad')),
                ('descipcionHabilidad', models.TextField(default='Desarrollador', max_length=2000, verbose_name='Descripcion de habilidad')),
            ],
            options={
                'verbose_name': 'Habilidades del usuario',
                'verbose_name_plural': 'Habilidades de los usuarios',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleName', models.CharField(max_length=50, verbose_name='Nombre del rol')),
            ],
            options={
                'verbose_name': 'perfil de usuario',
                'verbose_name_plural': 'perfiles',
            },
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Porcentaje', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Porcentaje de dominio de la habilidad')),
                ('udtHabilidad', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de actualizacion de la habilidad')),
                ('idHabilidades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.Habilidades', verbose_name='Id de la habilidad')),
                ('idUSuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.DatosUser', verbose_name='Id del usuario')),
            ],
            options={
                'verbose_name': 'Nivel de habilidad',
                'verbose_name_plural': 'Niveles de usuarios',
            },
        ),
        migrations.CreateModel(
            name='DetaRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Agregado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de agregacion del rol')),
                ('addUser', models.DateTimeField(auto_now=True, verbose_name='Fecha de agregacion de user')),
                ('EstadoRol', models.CharField(max_length=20, verbose_name='Estado del rol')),
                ('idRoles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.Roles', verbose_name='Id del rol')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.DatosUser', verbose_name='Id del usuario')),
            ],
            options={
                'verbose_name': 'Rol usuario',
                'verbose_name_plural': 'Roles de los usuarios',
            },
        ),
    ]
