# Generated by Django 2.2.12 on 2020-05-14 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userdata', '0002_auto_20200513_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategProye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lenguaje', models.CharField(max_length=45, verbose_name='Lenguaje')),
                ('motorDB', models.CharField(max_length=155, verbose_name='Motor de la base de datos')),
                ('arquitectura', models.CharField(max_length=155, verbose_name='Arquitectura')),
            ],
            options={
                'verbose_name': 'Categoria de proyecto',
                'verbose_name_plural': 'Categorias de proyectos',
            },
        ),
        migrations.CreateModel(
            name='TipoDocu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombTiDoc', models.CharField(max_length=45, verbose_name='Nombre del Tipo de documento')),
            ],
            options={
                'verbose_name': 'Tipo documento',
                'verbose_name_plural': 'Tipos de documento',
            },
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombProye', models.CharField(max_length=255, verbose_name='Nombre del proyecto')),
                ('descProy', models.TextField(max_length=2000, verbose_name='Descripcion del proyecto')),
                ('imgProye', models.ImageField(default='proye.png', upload_to='', verbose_name='Imagen del proyecto')),
                ('FechaIni', models.DateTimeField(verbose_name='Fecha de inicio del proyecto')),
                ('FechaFin', models.DateTimeField(verbose_name='Fecha del final del proyecto')),
                ('urlRepo', models.TextField(max_length=2000, verbose_name='Direccion del repositorio')),
                ('EstaProy', models.CharField(max_length=45, verbose_name='Estado del Proyecto')),
                ('idCategProye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.CategProye', verbose_name='Id de la categoria de proyecto')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombDocu', models.CharField(max_length=30, verbose_name='Nombre del documento')),
                ('pathDocu', models.TextField(max_length=2000, verbose_name='Direccion del git')),
                ('idProyectos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos', verbose_name='Id del proyecto')),
                ('idTipoDocu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.TipoDocu', verbose_name='Id del tipo de documento')),
                ('idUsuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.DatosUser', verbose_name='Id del usuario')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
    ]
